services:
  postgres:
    container_name: car_rest
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: car_rest_app
    volumes:
      - db:/var/lib/postgresql/data
      - .\src\main\resources\db\db_init.csv:/tmp/db_init.csv
    ports:
      - "5480:5432"
  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    restart: always
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: car_rest_app
      DB_SCHEMA: public
      DB_USER: postgres
      DB_PASSWORD: 1111
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8180:8080"
    depends_on:
      - postgres
volumes:
  db:
