spring:
  datasource:
    url: jdbc:postgresql://localhost:5480/car_rest_app
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: car_rest

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none

  flyway:
    default-schema: car_rest
    create-schemas: true

keycloak:
  realm: car-service-realm
  auth-server-url: http://localhost:8180/auth
  resource: car-service
  credentials:
    secret: Lkrcb5O89rRm01Fy8KiRX7DrYZlJ89fJ
  bearer-only: true
  ssl-required: external
  use-resource-role-mappings: true
